name: signal-api
services:
    signal-cli-rest-api:
        container_name: signal-api
        restart: always
        ports:
            - 8080:8080
        volumes:
            - /opt/docker/signal-api:/home/.local/share/signal-cli
        environment:
            - MODE=native
        image: bbernhard/signal-cli-rest-api
